set_property PACKAGE_PIN R1 [get_ports {cin}]
set_property PACKAGE_PIN M4 [get_ports {a0}]
set_property PACKAGE_PIN R2 [get_ports {a1}]
set_property PACKAGE_PIN P4 [get_ports {b0}]
set_property PACKAGE_PIN P5 [get_ports {b1}]
set_property IOSTANDARD LVCMOS33 [get_ports {cin}]
set_property IOSTANDARD LVCMOS33 [get_ports {a0}]
set_property IOSTANDARD LVCMOS33 [get_ports {a1}]
set_property IOSTANDARD LVCMOS33 [get_ports {b0}]
set_property IOSTANDARD LVCMOS33 [get_ports {b1}]

set_property PACKAGE_PIN K3 [get_ports {sum0}]
set_property PACKAGE_PIN M1 [get_ports {sum1}]
set_property PACKAGE_PIN K6 [get_ports {cout}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum0}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum1}]
set_property IOSTANDARD LVCMOS33 [get_ports {cout}]