set_property PACKAGE_PIN R1 [get_ports {SW1}]
set_property PACKAGE_PIN N4 [get_ports {SW2}]
set_property PACKAGE_PIN M4 [get_ports {SW3}]
set_property PACKAGE_PIN R2 [get_ports {SW4}]
set_property PACKAGE_PIN P2 [get_ports {SW5}]
set_property PACKAGE_PIN P5 [get_ports {SW8}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW1}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW2}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW3}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW4}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW5}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW8}]

set_property PACKAGE_PIN K3 [get_ports {LED0}]
set_property PACKAGE_PIN K6 [get_ports {LED3}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED3}]